### ISSUE TITLE
[Proposal] Presentation Layer에서 RequestParam 검증

### ISSUE THREAD

**Issue by sgh002400** [DDD-Community/DDD-8-Web2-Server#21]
## 제안 사항
- 요청으로 넘어온 쿼리 파라미터들을 컨트롤러에서 검증하자
- 3개 이상의 쿼리 파라미터는 객체로 묶자

</br>

## 제안 방식 장점
- Application layer에서 검증을 하면 요청에 대한 검증 로직이 애플리케이션 전체에 분산되고 코드 중복이 발생하며 비즈니스 로직에 검증 로직이 섞이게 되어 로직 추적이 어렵고 애플리케이션이 복잡해지는 문제가 발생합니다. 이로 인해 오류가 발생할 가능성을 높이게 되며 유지 보수에 상대적으로 높은 비용을 소모하게 됩니다. ([참고](https://meetup.nhncloud.com/posts/223))
  - 제안 방식을 통해 이를 해결할 수 있습니다.
 
- Presentation layer에서 검증에 실패하면 비즈니스 로직을 수행할 필요가 없어지므로 응답이 빨리지고 서버에 부하를 줄일 수 있습니다.

- 마지막으로 도움이 되기를 바라며 [참고한 영상 링크](https://www.youtube.com/watch?v=Ul-1lfjRCiE) 남깁니다 :)

**Comment by sgh002400** [comment]
## 제안 방식
- 요청으로 넘어온 쿼리 파라미터들을 컨트롤러에서 검증하자.
- 3개 이상의 쿼리 파라미터는 객체로 묶자

</br>

## 제안 방식 장점
- Application layer에서 검증을 하면 요청에 대한 검증 로직이 애플리케이션 전체에 분산되고 코드 중복이 발생하며 비즈니스 로직에 검증 로직이 섞이게 되어 로직 추적이 어렵고 애플리케이션이 복잡해지는 문제가 발생합니다. 이로 인해 오류가 발생할 가능성을 높이게 되며 유지 보수에 상대적으로 높은 비용을 소모하게 됩니다. ([참고](https://meetup.nhncloud.com/posts/223))
  - 제안 방식을 통해 이를 해결할 수 있습니다.
 
- Presentation layer에서 검증에 실패하면 비즈니스 로직을 수행할 필요가 없어지므로 응답이 빨리지고 서버에 부하를 줄일 수 있습니다.

**Comment by JIWEON-JEONG** [comment]
제안주신 방법에 대한 저의 생각은 이렇습니다.

물론 저도 요청DTO 를 통해 받아 Valid 또는 Validated 어노테이션을 통해 간결하게 검증을 할 수 있는 거에 대해서는 큰 장점이라고 생각하고,
저 또한 사용 하고 있습니다.

하지만, 이 어노테이션으로 검증을 하다 보면 분명한 한계점이 존재합니다.
1. 테스트가 어렵습니다. 
> 진행하려면 Mock test 를 통해 구현 해야 하며, 테스트를 진행 하는 시간 또한 단위테스트에 비해 큰 시간이 소요됩니다.
2. 가장 큰 부분인데 어노테이션을 통하여 구현 할 수 있는 검증이 한정적입니다. 
어노테이션으로 할 수 없는 검증 같은 경우, 로직이 들어가게 됩니다.
그렇게 되면 DataTranferObject 의 역할만 하는 것이 아닌 여러가지 역할을 하게 됨으로 좋지 않은 패턴을 가지게 됩니다.

**Valid 로 검증을 하지 말자 라는 것이 아닌, 간단한 NotNull 이나 패턴 같은 어노테이션으로 처리 할 수 있는 부분들은 처리 하고
그 외에 복잡한 검증 로직은 Service layer 에 들어가야 한다고 생각합니다.**

더하여 
> 3개 이상의 쿼리 파라미터는 객체로 묶자
해당 부분을 공감하면서도, GET 메서드는 요청메서드 이기 때문에 요청에 대한 정보가 URI 에 나타나는 이점을 놓치는 것은 아닐까 라는 생각도 듭니다.

**Comment by sgh002400** [comment]
같이 고민해주셔서 감사합니다 ☺️
1번 이유 같은 경우에는 크게 시간이 차이 나지 않는다면 테스트 시간이 길어지는 이유 때문에 많은 장점을 지닌 방식을 포기하기에는 약간 아쉬운 감이 있다는 생각이 들고, 2번 이유는 요청에 원하는 값이 없을 경우 기본값을 설정해주는 로직이기 때문에 Dto의 역할을 크게 벗어난 정도는 아니라는 생각이 드네요. 혹시나 어노테이션으로 유효성 검사를 할 수 없는 경우가 생긴다고 해도 검증을 서비스 레이어에서 하는 것보다는 오히려 Dto 생성자 혹은 컨트롤러 부분에서 검증하는게 좀 더 큰 범위에서 생각 했을 때 역할에 맞는게 아닌가 하는 생각도 들어요 :)
또한 복잡한 검증 로직은 서비스 레이어에 들어가야 한다고 생각하신다고 하셨는데 저는 처음 제안한 이유 때문에 좋은 방법이 아니지 않을까 싶은 생각도 드네요. 마지막으로 제가 PR을 좀 더 신경써서 올렸어야 하는데 사용 예시를 올리지 않아서 오해가 있던 것 같습니다ㅠㅠ 제안한 방식도 클라이언트는 그대로 URI를 사용하여 요청을 보낼 수 있습니다! 단지 서버 단에서 객체로 받는 점과 검증을 컨트롤러에서 진행한다는 차이가 있는 것이죠. 사용 예시는 PR에 추가해두겠습니다. 좋은 밤 되세요🌙

**Comment by JIWEON-JEONG** [comment]
<img width="832" alt="스크린샷 2023-01-11 오전 1 09 45" src="https://user-images.githubusercontent.com/80501465/211603417-0fa41e73-4700-4c9c-93e4-762c0a9f9c3f.png">

[마이다스 기술블로그](http://egloos.zum.com/mt1716/v/9291203)

**클라이언트 요청 데이터를 검증 하는 로직은 Application-Controller 계층 에서 하는게 맞아 보이네요.** 

제안주신 방법으로 해보겠습니다. 
덕분에 몰랐던 내용을 깊게 알아가는 것 같아요. 감사합니다.

> 개인적인 의문으로 남는것은 DTO 라는 객체가 데이터 매핑 및 전달 하는 역할과 검증 하는 역할 2가지 역할을 하는 것인가? 
그렇다면 DTO 가 아니라 DTO&Validator 가 되어야 하는 것은 아닌가 라는 의문이 남습니다.
아직 경험치가 낮아 생기는 의문이라 천천히 알아보고 이해가 되면 공유하겠습니다.
