### ISSUE TITLE
[Proposal] Secret Key 관리 방식 변경

### ISSUE THREAD

**Issue by sgh002400** [DDD-Community/DDD-8-Web2-Server#24]
### 장점
- `final` 키워드를 붙일 수 있게 되어 불변성을 유지할 수 있습니다.
- 타입에 안정적입니다.

</br>

### 단점
```java
@Service
@RequiredArgsConstructor
public class PlaceFeignService {
	private final SecretKeyConstructorProperties secretKeyConstructorProperties;
	private final String TMP = secretKeyConstructorProperties.getKakao().getRedirectUri();
        // 서버 실행시 -> error: variable secretKeyConstructorProperties might not have been initialized 발생!!!

~~
}
```
- 생성자 호출 단계 이전에 초기화를 할 수 없으므로 코드 중복이 발생합니다.
  - `@PostConstruct` 어노테이션으로 이 문제를 해결할 수는 있을 것 같지만 해당 어노테이션은 다른 리소스에서 호출되지 않아도 수행되기 때문에 많은 클래스에서 호출해야 되는 상황엔 부적절하지 않나 하는 고민이 되네욥 🧐

</br>

제안하는 방식 어떻게 생각하시는지와 만약 이 방식 사용을 찬성하신다면 약간의 중복을 허용하는 것과 `@PostConstruct` 어노테이션을 사용하는 방향 중에 어떤 것이 괜찮다고 생각하시는지 궁금합니다 :)

[참고한 블로그 링크](https://tecoble.techcourse.co.kr/post/2020-09-29-spring-properties-binding/) 남길게요 😁

**Comment by JIWEON-JEONG** [comment]
먼저 깔끔한 정리 너무 감사합니다.

약간의 중복이라는 것은 제가 이해하기로는 각 메서드마다 final 필드를 정의하여, 메서드마다 중복되는 필드가 있을수 있다 라는 걸로 이해해도 될까요?

저는 PostConstruct 를 쓰는것이 조금 더 최적화 되어있는 거같아요. (사실 정답이 있다기 보다는 무엇을 선택하냐에 문제 같아요..)
> @PostConstruct 어노테이션으로 이 문제를 해결할 수는 있을 것 같지만 해당 어노테이션은 다른 리소스에서 호출되지 않아도 수행되기 때문에 많은 클래스에서 호출해야 되는 상황엔 부적절하지 않나 하는 고민이 되네욥 🧐

이 부분에 대해서는 Spring 어플리케이션이 뜰때 한번 수행되기 때문에 큰 성능이슈는 없을 것 같다는 생각입니다.
환경변수를 사용하는 클래스에서 미리 PostConstruct 가 실행 되겠지만, final 이기 때문에 결국 한번만 생성이 될 것이고,
**중복 코드가 발생하는 일**을 막을 수 있기 때문에 완성도 측면에서도 조금 더 유리 하지 않나 라는 의견입니다.

**Comment by sgh002400** [comment]
> 먼저 깔끔한 정리 너무 감사합니다.
> 
> 약간의 중복이라는 것은 제가 이해하기로는 각 메서드마다 final 필드를 정의하여, 메서드마다 중복되는 필드가 있을수 있다 라는 걸로 이해해도 될까요?
> 
> 저는 PostConstruct 를 쓰는것이 조금 더 최적화 되어있는 거같아요. (사실 정답이 있다기 보다는 무엇을 선택하냐에 문제 같아요..)
> 
> > @PostConstruct 어노테이션으로 이 문제를 해결할 수는 있을 것 같지만 해당 어노테이션은 다른 리소스에서 호출되지 않아도 수행되기 때문에 많은 클래스에서 호출해야 되는 상황엔 부적절하지 않나 하는 고민이 되네욥 🧐
> 
> 이 부분에 대해서는 Spring 어플리케이션이 뜰때 한번 수행되기 때문에 큰 성능이슈는 없을 것 같다는 생각입니다. 환경변수를 사용하는 클래스에서 미리 PostConstruct 가 실행 되겠지만, **중복 코드가 발생하는 일**을 막을 수 있기 때문에 완성도 측면에서도 조금 더 유리 하지 않나 라는 의견입니다.

네 지원님이 이해하신대로 각 메서드마다 상수를 생성해줘야 되는 중복도 있고 secret key를 사용하려는 클래스마다 `SecretKeyConstructorProperties`를 주입 받아야 되는 중복도 있습니다.
지원님 말씀을 듣고 다시 생각해보니 스프링이 뜰 때 한번 수행되는 정도면 `@PostConstruct` 어노테이션을 활용하는게 좀 더 나은 것 같네요 :) 좋은 의견 감사합니다 🙏

**Comment by sgh002400** [comment]
`@PostConstruct` 사용하지 않는 방향으로 결정 : https://github.com/DDD-Community/DDD-8-Web2-Server/pull/23#issuecomment-1382047807
