### ISSUE TITLE
[Proposal] DTO 처리 방식에 대하여.

### ISSUE THREAD

**Issue by JIWEON-JEONG** [DDD-Community/DDD-8-Web2-Server#8]
## 제안하는 DTO 방식 
각 도메인에는 Request, Response 클래스가 있고 DTO 클래스들은 내부 정적 클래스로 관리 합니다.

## 이점 
- 해당 역할을 담은 가독성 좋은 이름으로 사용 할 수 있습니다.
- DTO 클래스 본인의 역할에 맞는 파일에서 한꺼번에 관리 할 수 있으며 **응집도를 높일 수 있습니다.**

### Inner 클래스의 메모리 leak 
> Inner 클래스 특성 상 바깥 클래스와의 외부 참조가 발생 할 수 있다.  참조를 저장하기 위한 리소스와 저장 공간에 대한 리소스 등이 발생 하며,
가비지 컬렉션이 바깥 클래스의 인스턴스를 수거하지 못하는 메모리 누수가 생길 수 있다.

### 내부 클래스를 static 정적 클래스로 관리하자.
static 내부 클래스는 자신의 바깥 클래스 인스턴스의 임시적 참조를 유지하지 않는다. 즉 static 내부 클래스로 선언하면 메모리 누수의 일반적인 원인을 예방할 수 있고, 클래스의 각 인스턴스당 더 적은 메모리를 사용하게 된다.

## 사용 예시
~~~
public class ResponseDto {
    
    public static class JoinForm {
        private String loginId;
        private String password;
        private String email;
    }
    
    public static class LoginForm {
        private String loginId;
        private String password;
    }
}

public static void main(String[] args) {
      XXX =  new ResponseDto.LoginForm();
}
~~~

## 참조
[링크](https://johngrib.github.io/wiki/java-inner-class-may-be-static/)

**Comment by sgh002400** [comment]
먼저 좋은 방법 고민하고 제안해주셔서 감사합니다! 발생할 수 있는 문제점 미리 생각해보고 해결 방안을 고민해 본 점이 인상 깊네요 ☺️ 

그런데 제안해주신 방식에서 첫번째 장점인 `가독성 좋은 이름으로 사용할 수 있다`는 것은 이미 사용하고 있는 정적 팩토리 메서드 패턴의 장점이기 때문에 사실 제안해주신 이 방식의 가장 큰 장점은 DTO들을 하나의 클래스 안에 관리함으로써 응집도를 높일 수 있다는 것 같아요!

하지만 Request 클래스 안에 모든 요청과 관련된 DTO들을 넣고, Response 클래스 안에 모든 응답과 관련된 DTO들을 넣는건 결국 `파일 수를 줄이고 한 파일 내의 코드 수를 늘리느냐 vs 한 파일 내의 코드 수를 줄이고 파일 수를 늘리느냐` 정도의 차이 밖에 없는 것 같고 오히려 응답 시 불필요한 객체를 하나 더 생성해야 되는 것과 그로 인해 클라이언트에서 응답 객체를 한번 더 까봐야 한다는 약간의 번거로움을 추가하는 것 같다는 생각이예요. 그럼에도 기존 지원님의 아이디어인 수 많은 DTO 클래스들을 줄이면서 응집력을 높이는 것에는 동의하기 때문에 만약 이 방법을 사용한다고 하신다면 저는 예를 들어 SignUpDto 클래스 내부에 Request 클래스와 Response 클래스를 두는 방식을 사용해보는 것을 제안드립니다 :)
